# Generated by Django 5.1.7 on 2025-03-25 17:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('job_title_hindi', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(default='', max_length=250, unique_for_date='date_posted')),
                ('short_description', models.TextField()),
                ('short_description_hindi', models.TextField(default='')),
                ('long_description', models.TextField(default='')),
                ('long_description_hindi', models.TextField(default='')),
                ('company_name', models.CharField(max_length=250)),
                ('company_name_hindi', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='job_images')),
                ('how_to_apply_video', models.URLField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_hindi', models.TextField(default='')),
                ('answer', models.TextField()),
                ('answer_hindi', models.TextField(default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_name', models.CharField(max_length=250)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='jobApplyLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('desc', models.TextField()),
                ('desc_hindi', models.TextField(default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobImportantDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_hindi', models.CharField(default='', max_length=250)),
                ('value', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_hindi', models.CharField(default='', max_length=250)),
                ('no_of_opening', models.IntegerField()),
                ('desc', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobQualifyAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Own_tags', models.CharField(max_length=100)),
                ('Government', models.BooleanField(default=False)),
                ('Private', models.BooleanField(default=False)),
                ('internship', models.BooleanField(default=False)),
                ('Fulltime', models.BooleanField(default=False)),
                ('Exam', models.BooleanField(default=False)),
                ('result', models.BooleanField(default=False)),
                ('category_flags', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.job')),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['date_posted'], name='Jobs_job_date_po_53c74a_idx'),
        ),
    ]
