# Generated by Django 5.0.3 on 2024-03-22 04:00

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tag_1',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tag_2',
        ),
        migrations.AddField(
            model_name='tags',
            name='discription',
            field=models.TextField(default=datetime.datetime(2024, 3, 22, 4, 0, 17, 193071, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='long_description',
            field=models.TextField(default=''),
        ),
    ]
