# Generated by Django 5.0.3 on 2024-05-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_remove_tags_tag_1_remove_tags_tag_2_tags_discription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tag',
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_type1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_type2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_type3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tags',
            name='tags',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
