# Generated by Django 5.0.3 on 2024-05-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_rename_tag_type1_tags_is_featured_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='category_flags',
            new_name='other_tags',
        ),
        migrations.AlterField(
            model_name='tags',
            name='Tagss',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tags',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
