# Generated by Django 5.0.3 on 2024-05-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_rename_category_flags_tags_other_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='other_tags',
            new_name='category_flags',
        ),
        migrations.AlterField(
            model_name='tags',
            name='Tagss',
            field=models.CharField(max_length=100),
        ),
    ]
