# Generated by Django 5.0.3 on 2024-05-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_rename_other_tags_tags_category_flags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='Tagss',
            new_name='tagss',
        ),
    ]
