# Generated by Django 5.0.3 on 2024-05-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0007_rename_tagss_tags_tagss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='is_active',
            new_name='Exam',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='is_featured',
            new_name='Fulltime',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='is_important',
            new_name='Government',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_tag',
        ),
        migrations.AddField(
            model_name='tags',
            name='Private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tags',
            name='internship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tags',
            name='result',
            field=models.BooleanField(default=False),
        ),
    ]
