# Generated by Django 5.0.3 on 2024-06-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0008_rename_is_active_tags_exam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tagss',
            new_name='Own_tags',
        ),
    ]
